[project]
name = "proyectofinalentorno"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "airflowctl>=0.2.11",
    "apache-airflow>=2.9.3",
    "beautifulsoup4>=4.13.3",
    "confluent-kafka>=2.9.0",
    "lxml>=5.3.1",
    "pandas>=2.2.3",
    "pendulum>=3.0.0",
    "plotly>=6.0.0",
    "py7zr>=0.22.0",
    "pyarrow>=19.0.1",
    "pyspark[connect]==3.5.1",
    "pysqlite3-binary>=0.5.4",
    "pyzmq>=26.3.0",
    "scikit-learn>=1.6.1",
    "toml>=0.10.2",
    "ujson>=5.10.0",
]

[tools.project_paths]
db_path = "/tmp/airflow_etl.db"
pathToData = "data/raw/"
countries_dict_path = "data/paisesDict.json"
processed_data_path = "data/processed"

[tools.address]
'bootstrap.servers' = "docker01.aulas.eif.urjc.es:9092"
